###################################
# config file for genome assembly #
directories:
  workDir : "/work/FAC/FBM/DMF/pengel/spirit/gsartonl/assembly/" # To adapt
  rawReadsDir: "00_rawReads"
  fastQC: "01_FastQC"
  trimmedReads: "02_trimmed"
  assembly: "03_assembly"
  annotation : "04_annotation"
  checkM : "assemblyQC/checkM"
  readCoverage: "assemblyQC/readCoverage"

# samples
SAMPLES : "ESL0744"
LIBRARY:
  ESL0744 :
    Lane: "2"
    Hash_FWD : "FDSW210446598-1r_HMWTJDSX2"
    Hash_REV : "FDSW210446598-1r_HMWTJDSX2"

suffix : ".fq.gz"

illuminaAdaptors :
  - setup/AllIllumina-PEadapters.fa

FilterContigs:
  length: "500"
  coverage : "10"
